version: '3.8'

services:
  # 1. Laravel App Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: subscription-service-app
    container_name: subscription_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      APP_SERVICE: app
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: subscription_db
      DB_USERNAME: root
      DB_PASSWORD: root
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - laravel-network

  # 2. MySQL Database Service
  db:
    image: mysql:8.0
    container_name: subscription_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: subscription_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: user
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "33061:3306" # Host port 33061 maps to Container 3306 (to avoid conflict with local MySQL)
    networks:
      - laravel-network

# Networks
networks:
  laravel-network:
    driver: bridge

# Volumes for persistent data
volumes:
  dbdata:
    driver: local